CREATE TABLE users (
    ID UUID NOT NULL UNIQUE,
    NAME VARCHAR(300) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    PASSWORD VARCHAR(150) NOT NULL,
    BIRTHDAY DATE,
    IMAGE_URL VARCHAR(150),

    PRIMARY KEY (ID)
);